In [23]:
import pandas as pd

df_cfb = pd.read_csv('cfb22.csv')
df_ap = pd.read_csv(r'C:\Users\idixo\OneDrive - Bentley University\ap_top25_2022 (1) (1).csv')

df_cfb.head()

,Unnamed: 0,Off Rank,Team,Games,Win-Loss,Off Plays,Off Yards,Off Yards/Play,Off TDs,Off Yards per Game,...,Average Time of Possession per Game,Turnover Rank,Fumbles Recovered,Opponents Intercepted,Turnovers Gain,Fumbles Lost,Interceptions Thrown_y,Turnovers Lost,Turnover Margin,Avg Turnover Margin per Game
0,0,1,Tennessee (SEC),13,11-2,945,6832,7.23,78,525.5,...,25:02,10,11,11,22,8,3,11,11,0.85
1,1,2,Washington (Pac-12),13,11-2,975,6705,6.88,65,515.8,...,31:21,61,5,7,12,2,9,11,1,0.08
2,2,3,Southern California (Pac-12),14,11-3,988,7092,7.18,73,506.6,...,31:57,1,10,19,29,2,5,7,22,1.57
3,3,4,UCLA (Pac-12),13,9-4,934,6547,7.01,65,503.6,...,27:40,85,7,11,18,9,12,21,-3,-0.23
4,4,5,Georgia (SEC),15,15-0,1049,7517,7.17,75,501.1,...,33:37,66,7,12,19,11,7,18,1,0.07

In [24]:
df_cfb = df_cfb.drop(columns=['Unnamed: 0'])

In [25]:
df_cfb['Team'] = df_cfb['Team'].str.replace(r'\s*\(.*\)', '', regex=True)

In [26]:
df_cfb.head()
df_ap.head()

   AP Rank        Team  AP Poll Points  Wins  Losses
0        1     Georgia            1575    15       0
1        2         TCU            1490    13       2
2        3    Michigan            1400    13       1
3        4  Ohio State            1340    11       2
4        5     Alabama            1270    11       2

In [27]:
name_fixes = {
    'Ohio State': 'Ohio St.',
    'Penn State': 'Penn St.',
    'Kansas State': 'Kansas St.',
    'USC': 'Southern California',
    'Florida State': 'Florida St.',
    'Oregon State': 'Oregon St.',
    'Mississippi State': 'Mississippi St.',
    'Fresno State': 'Fresno St.'
}

df_ap['Team'] = df_ap['Team'].replace(name_fixes)

In [28]:
df_merged = pd.merge(df_cfb, df_ap, on='Team', how='inner')
df_merged.head()

,Off Rank,Team,Games,Win-Loss,Off Plays,Off Yards,Off Yards/Play,Off TDs,Off Yards per Game,Def Rank,...,Turnovers Gain,Fumbles Lost,Interceptions Thrown_y,Turnovers Lost,Turnover Margin,Avg Turnover Margin per Game,AP Rank,AP Poll Points,Wins,Losses
0,1,Tennessee,13,11-2,945,6832,7.23,78,525.5,91,...,22,8,3,11,11,0.85,6,1180,11,2
1,2,Washington,13,11-2,975,6705,6.88,65,515.8,60,...,12,2,9,11,1,0.08,8,1040,11,2
2,3,Southern California,14,11-3,988,7092,7.18,73,506.6,106,...,29,2,5,7,22,1.57,12,840,11,3
3,4,UCLA,13,9-4,934,6547,7.01,65,503.6,87,...,18,9,12,21,-3,-0.23,17,640,9,4
4,5,Georgia,15,15-0,1049,7517,7.17,75,501.1,10,...,19,11,7,18,1,0.07,1,1575,15,0

In [29]:
df_merged = df_merged.sort_values(by='AP Rank')
df_merged.head(25)

,Off Rank,Team,Games,Win-Loss,Off Plays,Off Yards,Off Yards/Play,Off TDs,Off Yards per Game,Def Rank,...,Turnovers Gain,Fumbles Lost,Interceptions Thrown_y,Turnovers Lost,Turnover Margin,Avg Turnover Margin per Game,AP Rank,AP Poll Points,Wins,Losses
4,5,Georgia,15,15-0,1049,7517,7.17,75,501.1,10,...,19,11,7,18,1,0.07,1,1575,15,0
11,27,TCU,15,13-2,1020,6825,6.69,70,455.0,95,...,22,8,8,16,6,0.40,2,1490,13,2
10,24,Michigan,14,13-1,970,6423,6.62,65,458.8,6,...,18,4,6,10,8,0.57,3,1400,13,1
6,9,Ohio St.,13,11-2,876,6379,7.28,72,490.7,14,...,18,4,6,10,8,0.62,4,1340,11,2
8,11,Alabama,13,11-2,896,6202,6.92,63,477.1,13,...,14,8,8,16,-2,-0.15,5,1270,11,2
0,1,Tennessee,13,11-2,945,6832,7.23,78,525.5,91,...,22,8,3,11,11,0.85,6,1180,11,2
14,34,Penn St.,13,11-2,911,5637,6.19,57,433.6,17,...,26,8,7,15,11,0.85,7,1120,11,2
1,2,Washington,13,11-2,975,6705,6.88,65,515.8,60,...,12,2,9,11,1,0.08,8,1040,11,2
13,31,Tulane,14,12-2,936,6179,6.60,64,441.4,47,...,21,11,5,16,5,0.36,9,960,12,2
9,17,Utah,14,10-4,1006,6536,6.50,69,466.9,27,...,24,8,10,18,6,0.43,10,920,10,3
16,41,Kansas St.,14,10-4,958,5863,6.12,53,418.8,64,...,24,6,6,12,12,0.86,11,880,10,3
2,3,Southern California,14,11-3,988,7092,7.18,73,506.6,106,...,29,2,5,7,22,1.57,12,840,11,3
7,10,Florida St.,13,10-3,904,6295,6.96,61,484.2,15,...,16,7,7,14,2,0.15,13,800,10,3
21,61,Oregon St.,13,10-3,846,5148,6.09,52,396.0,26,...,17,5,13,18,-1,-0.08,14,760,10,3
5,6,Oregon,13,10-3,940,6507,6.92,64,500.5,71,...,21,3,9,12,9,0.69,15,720,10,3
12,28,LSU,14,10-4,997,6344,6.36,62,453.1,41,...,20,12,7,19,1,0.07,16,680,10,4
3,4,UCLA,13,9-4,934,6547,7.01,65,503.6,87,...,18,9,12,21,-3,-0.23,17,640,9,4
20,60,Notre Dame,13,9-4,870,5150,5.92,50,396.2,22,...,15,7,11,18,-3,-0.23,18,600,9,4
23,73,South Carolina,13,8-5,832,4925,5.92,50,378.8,89,...,23,13,14,27,-4,-0.31,19,560,8,4
22,62,Mississippi St.,13,9-4,929,5108,5.50,48,392.9,35,...,23,10,9,19,4,0.31,20,520,9,4
17,48,Clemson,14,11-3,1026,5744,5.60,55,410.3,28,...,21,12,10,22,-1,-0.07,21,480,11,3
18,50,Pittsburgh,13,9-4,912,5275,5.78,43,405.8,23,...,22,9,11,20,2,0.15,22,440,9,4
19,53,Fresno St.,14,10-4,939,5639,6.01,50,402.8,31,...,18,5,9,14,4,0.29,23,400,10,3
24,95,Troy,14,12-2,897,5038,5.62,41,359.9,19,...,27,6,15,21,6,0.43,24,360,10,3
15,35,Texas,13,8-5,875,5584,6.38,51,429.5,54,...,14,5,7,12,2,0.15,25,320,10,3

In [30]:
df_merged[['Team', 'AP Rank']].head(25)

                   Team  AP Rank
4               Georgia        1
11                  TCU        2
10             Michigan        3
6              Ohio St.        4
8               Alabama        5
0             Tennessee        6
14             Penn St.        7
1            Washington        8
13               Tulane        9
9                  Utah       10
16           Kansas St.       11
2   Southern California       12
7           Florida St.       13
21           Oregon St.       14
5                Oregon       15
12                  LSU       16
3                  UCLA       17
20           Notre Dame       18
23       South Carolina       19
22      Mississippi St.       20
17              Clemson       21
18           Pittsburgh       22
19           Fresno St.       23
24                 Troy       24
15                Texas       25

In [32]:
df_merged.columns

Index(['Off Rank', 'Team', 'Games', 'Win-Loss', 'Off Plays', 'Off Yards',
       'Off Yards/Play', 'Off TDs', 'Off Yards per Game', 'Def Rank',
       ...
       'Turnovers Gain', 'Fumbles Lost', 'Interceptions Thrown_y',
       'Turnovers Lost', 'Turnover Margin', 'Avg Turnover Margin per Game',
       'AP Rank', 'AP Poll Points', 'Wins', 'Losses'],
      dtype='str', length=154)

In [34]:
project_cols = [
    'Team',
    'AP Rank',
    'AP Poll Points',
    'Wins',
    
    # Offense
    'Points Per Game',
    'Off Yards per Game',
    'Off Yards/Play',
    
    # Defense
    'Avg Points per Game Allowed',
    'Yards Per Game Allowed',
    
    # Efficiency
    'Turnover Margin',
    'Avg Turnover Margin per Game',
    
    # Rushing vs Passing
    'Rushing Yards per Game',
    'Pass Yards Per Game'
]

In [35]:
df_project = df_merged[project_cols]
df_project.head()

,Team,AP Rank,AP Poll Points,Wins,Points Per Game,Off Yards per Game,Off Yards/Play,Avg Points per Game Allowed,Yards Per Game Allowed,Turnover Margin,Avg Turnover Margin per Game,Rushing Yards per Game,Pass Yards Per Game
4,Georgia,1,1575,15,41.1,501.1,7.17,14.3,296.8,1,0.07,205.3,295.8
11,TCU,2,1490,13,38.8,455.0,6.69,29.0,408.2,6,0.40,193.3,261.7
10,Michigan,3,1400,13,40.4,458.8,6.62,16.1,292.1,8,0.57,238.9,219.9
6,Ohio St.,4,1340,11,44.2,490.7,7.28,21.0,321.5,8,0.62,192.4,298.3
8,Alabama,5,1270,11,41.1,477.1,6.92,18.2,318.2,-2,-0.15,195.5,281.5

In [36]:
corr = df_project.corr(numeric_only=True)

print(corr['AP Rank'].sort_values())

AP Poll Points                 -0.988429
Points Per Game                -0.769752
Wins                           -0.738661
Off Yards/Play                 -0.690965
Off Yards per Game             -0.634314
Rushing Yards per Game         -0.484460
Avg Turnover Margin per Game   -0.296990
Turnover Margin                -0.295514
Pass Yards Per Game            -0.283635
Yards Per Game Allowed          0.099449
Avg Points per Game Allowed     0.169961
AP Rank                         1.000000
Name: AP Rank, dtype: float64